// ActionType.js

export const ADD_COUNTER = 'ADD_COUNTER';
export const REMOVE_COUNTER = 'REMOVE_COUNTER';

export const ADD_COUNTER_REQUEST = 'ADD_COUNTER_REQUEST';
export const REMOVE_COUNTER_REQUEST = 'REMOVE_COUNTER_REQUEST';

export const REQUESTED_DOG = 'REQUESTED_DOG';
export const REQUESTED_DOG_SUCCEEDED = 'REQUESTED_DOG_SUCCEEDED';
export const REQUESTED_DOG_FAILED = 'REQUESTED_DOG_FAILED';
export const FETCHED_DOG = 'FETCHED_DOG';



